[[CutBranching]]
arch = "aarch64"
git-tree-sha1 = "2930ba8d7efe4865e4d41307c44ecf4100fdf32e"
os = "macos"

    [[CutBranching.download]]
    sha256 = "aa3dfffb966874c926c920d12f7ac5f60ee32632d8524916b4042e8dfc0e4258"
    url = "https://github.com/JuliaBinaryWrappers/CutBranching_jll.jl/releases/download/CutBranching-v0.1.0+0/CutBranching.v0.1.0.aarch64-apple-darwin.tar.gz"
[[CutBranching]]
arch = "aarch64"
git-tree-sha1 = "a69521790145364e239dede3a6a73cb2e23ebed1"
libc = "glibc"
os = "linux"

    [[CutBranching.download]]
    sha256 = "34f187f4104345e52904cb1c07ed9f97789878d3156c0351c091927902f62b60"
    url = "https://github.com/JuliaBinaryWrappers/CutBranching_jll.jl/releases/download/CutBranching-v0.1.0+0/CutBranching.v0.1.0.aarch64-linux-gnu.tar.gz"
[[CutBranching]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f733d2a044b28dca351ac69247e9254c845d8eef"
libc = "glibc"
os = "linux"

    [[CutBranching.download]]
    sha256 = "fa51c6040ce893dced84aa9a975c21f901ffc65c1253fec46b169efd1af103b0"
    url = "https://github.com/JuliaBinaryWrappers/CutBranching_jll.jl/releases/download/CutBranching-v0.1.0+0/CutBranching.v0.1.0.armv6l-linux-gnueabihf.tar.gz"
[[CutBranching]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f024c1126a7485bf36b5f40a52e23c79443a7538"
libc = "glibc"
os = "linux"

    [[CutBranching.download]]
    sha256 = "f4d484a1e7f7654fdaf1e3d664452801aec07feff09eda440f6bf03710f0b042"
    url = "https://github.com/JuliaBinaryWrappers/CutBranching_jll.jl/releases/download/CutBranching-v0.1.0+0/CutBranching.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[CutBranching]]
arch = "i686"
git-tree-sha1 = "a9cf2468174d402bd1b33e32c002def28da55847"
libc = "glibc"
os = "linux"

    [[CutBranching.download]]
    sha256 = "eb0782587d0e81fdf7d52a237b9492c1b58f3dfd94ccc1685f16985f397a08ed"
    url = "https://github.com/JuliaBinaryWrappers/CutBranching_jll.jl/releases/download/CutBranching-v0.1.0+0/CutBranching.v0.1.0.i686-linux-gnu.tar.gz"
[[CutBranching]]
arch = "powerpc64le"
git-tree-sha1 = "076bcdb41c1bc90bdb6f31fcfe999e47128a531f"
libc = "glibc"
os = "linux"

    [[CutBranching.download]]
    sha256 = "5fee66ce7beb7a5b79ec6531e0a6d9f58bfb85a227a66791d5657a9efea8f632"
    url = "https://github.com/JuliaBinaryWrappers/CutBranching_jll.jl/releases/download/CutBranching-v0.1.0+0/CutBranching.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[CutBranching]]
arch = "x86_64"
git-tree-sha1 = "8d32ab45cad1fbb716dbcbf30bffe43c0b4c9a18"
os = "macos"

    [[CutBranching.download]]
    sha256 = "0ad85aa7e1a8e79c1d1fe41c76fe5af5336ace031dd236783bba95a9808cda08"
    url = "https://github.com/JuliaBinaryWrappers/CutBranching_jll.jl/releases/download/CutBranching-v0.1.0+0/CutBranching.v0.1.0.x86_64-apple-darwin.tar.gz"
[[CutBranching]]
arch = "x86_64"
git-tree-sha1 = "d437b311363b163da33dd91e82a3cbc8f532fd05"
libc = "glibc"
os = "linux"

    [[CutBranching.download]]
    sha256 = "abb77d2a475c35e44c8f8f9e0e9bc1ef905888fc6df01d3eaa39ab9b127bb875"
    url = "https://github.com/JuliaBinaryWrappers/CutBranching_jll.jl/releases/download/CutBranching-v0.1.0+0/CutBranching.v0.1.0.x86_64-linux-gnu.tar.gz"
[[CutBranching]]
arch = "x86_64"
git-tree-sha1 = "e44d5a7dd60fc3ccb6c888982e62c0470db1a51d"
os = "freebsd"

    [[CutBranching.download]]
    sha256 = "bb33f1c541974f83f3fd7a6fa3a761457a41b82d04e74a49b3c745bd62641e4e"
    url = "https://github.com/JuliaBinaryWrappers/CutBranching_jll.jl/releases/download/CutBranching-v0.1.0+0/CutBranching.v0.1.0.x86_64-unknown-freebsd.tar.gz"
